site_name: LowDragMC
copyright: Copyright &copy; 2019 - 2025 KilaBash
site_url: https://github.com/Low-Drag-MC
repo_url: https://github.com/Low-Drag-MC
repo_name: Low-Drag-MC
theme:
  name: material
  logo: assets/icon.png
  icon:
    favicon: assets/icon.png
    touchicon: assets/icon.png
  language: en 
  pygments_style: friendly
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
  alternate:
    - name: English
      link: /en/ 
      lang: en
    # - name: 中文
    #   link: /zh/
    #   lang: zh
extra_css:
  - css/custom.css
plugins:
  - search
  - macros
  - glightbox
  - tags
  - awesome-pages
markdown_extensions:
  - attr_list
  - tables
  - md_in_html
  - pymdownx.emoji
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true


